"""Configuration. Precedence: environment variables > ~/.engram/config.toml > defaults.

To keep the package distributable, nothing here depends on where the code is
installed. Per-user values such as the memory storage location are persisted
in config.toml (generated by `engram setup`).
"""

from __future__ import annotations

import os
import tomllib
from dataclasses import dataclass, field, fields
from pathlib import Path


def _engram_home() -> Path:
    # Keep SQLite off synced folders (Google Drive, etc.) since sync clients
    # risk corrupting the lock file. Use ~/.engram rather than %LOCALAPPDATA%,
    # which can be virtualized under an MSIX sandbox.
    return Path(os.environ.get("ENGRAM_HOME", str(Path.home() / ".engram")))


@dataclass(frozen=True)
class Settings:
    # --- Layout ---
    memories_dir: Path = field(
        default_factory=lambda: _engram_home() / "memories"
    )
    data_dir: Path = field(default_factory=_engram_home)

    # --- Embedding (English edition default: all-MiniLM-L6-v2, mean pooling,
    # no query/doc prefixes; prefix-style models such as E5 or Ruri can be
    # configured via embed_model / query_prefix / doc_prefix) ---
    embed_model: str = "sentence-transformers/all-MiniLM-L6-v2"
    # Backend selection. "auto" uses ONNX (lightweight, 1-2s startup) once
    # export-onnx has produced a model, falling back to torch
    # (sentence-transformers, heavy import) if it hasn't been generated yet.
    # "onnx" / "torch" force one or the other. See embedder.make_embedder.
    embed_backend: str = "auto"          # "auto" | "onnx" | "torch"
    query_prefix: str = ""
    doc_prefix: str = ""

    # --- Re-rank weights (relevance dominates, to prevent a rich-get-richer
    # loop where activation alone drives ranking) ---
    w_relevance: float = 0.6
    w_activation: float = 0.25
    w_importance: float = 0.15
    # Floor for the within-candidate-set min-max normalization of relevance
    # (dynamics.normalize_relevances). Guards against the range compression
    # of cosine similarity — with prefix-style Japanese models such as
    # Ruri-v3, cosine similarities compress into 0.8-0.87 — which flattens
    # relevance's discriminative power and lets the activation floor dominate
    # ranking. When the spread across candidates is below this floor, the
    # normalization does not amplify it; instead it scales relevance's
    # contribution down in proportion to the actual difference. Moving this
    # closer to 0 amplifies even tiny differences at full strength (not
    # recommended). Ranking-only: reported values and thresholds always use
    # the raw score.
    relevance_norm_floor: float = 0.10

    # --- Access-event weights ---
    recall_hit_weight: float = 0.3   # merely returned by recall (weak reinforcement)
    reinforce_weight: float = 1.0    # reported as "actually useful" (strong reinforcement)
    reinforce_strength_max: float = 3.0
    create_alpha: float = 2.0        # initial encoding boost: w = 1 + alpha * (importance/10)

    # --- Decay (flashbulb memory: higher importance decays more slowly) ---
    decay_base: float = 0.5
    decay_spread: float = 0.2        # d_i = clamp(base - spread*(imp-5)/5, min, max)
    decay_min: float = 0.3
    decay_max: float = 0.6
    min_elapsed_seconds: float = 60.0  # floor on elapsed time to prevent t^-d from diverging right after access

    # --- Search ---
    candidate_k: int = 50            # candidate count per source (vector/FTS)
    rrf_k: int = 60                  # Reciprocal Rank Fusion constant
    # Cosine similarity at or above this is treated as a duplicate. Ruri-v3
    # tends to score high cosine even between distinct short Japanese
    # sentences on the same topic; at 0.92 we observed distinct facts being
    # merged in practice, so this was raised to 0.95 (2026-06-11).
    dup_threshold: float = 0.95
    deep_score_threshold: float = 0.35  # auto-trigger deep recall when fast's top score is below this
    hop_decay: float = 0.7           # per-hop decay for spreading activation
    max_hops: int = 2

    # --- Exhaustive recall (surfacing memories that have sunk out of reach) ---
    # fast/deep both factor in activation, so a memory that hasn't been used
    # in a long time can sink below the cutoff in the final score even when
    # it's highly relevant (defeating the "never forgotten" property).
    # exhaustive ignores activation and ranks purely by relevance across all
    # tiers/types, so a sunken memory that's still semantically close will
    # always surface.
    exhaustive_min_relevance: float = 0.30    # relevance below this is never returned (noise gate)
    exhaustive_score_threshold: float = 0.30  # auto-trigger exhaustive when deep's top score is below this

    # --- Startup index reconciliation (multi-machine sharing) ---
    # Memory Markdown files may be shared (e.g. via Google Drive) while
    # index.db stays local to each machine, so a memory written on another
    # machine can be missing from this machine's index and invisible to
    # recall. On MCP server startup we compare the Markdown (non-trash) count
    # against the index (active) count and detect drift:
    #   "auto" = reindex automatically / "warn" = warn on stderr / "off" = do nothing
    startup_index_check: str = "auto"   # "auto" | "warn" | "off"

    # --- Hebbian co-linking ---
    colink_increment: float = 0.1
    colink_max: float = 1.0

    # --- Correction (hypercorrection effect) ---
    correction_min_importance: int = 7

    # --- Consolidation (sleep) ---
    consolidate_min_age_days: int = 14
    consolidate_cluster_sim: float = 0.75

    # --- Automatic consolidation nudge ---
    # engram has no LLM of its own, so summarization (the core of
    # consolidation) can only be done by the agent. SessionEnd tallies the
    # number of candidate clusters, and if it exceeds the threshold,
    # UserPromptSubmit nudges the agent to do the consolidation work via
    # additionalContext (see hooks.py).
    consolidate_nudge: bool = True
    consolidate_nudge_min_clusters: int = 3     # nudge once at least this many clusters exist
    consolidate_nudge_interval_days: float = 7.0  # minimum interval between nudges

    # --- Skill-extraction candidates (skill nudge) ---
    # A mechanism structurally similar to consolidation. When episodes
    # recording "the same shape of work" form a cluster of at least a
    # certain size (the "rule of three"), it's judged worth extracting as a
    # reusable procedure (a skill), and the agent is nudged to propose it to
    # the user. Unlike consolidation, no age filter is applied, since we
    # specifically want to target recently repeated work.
    skill_nudge: bool = True
    skill_min_count: int = 3            # a cluster needs at least this many episodes to be a skill candidate (rule of three)
    # Cosine threshold above which episodes are considered procedurally
    # similar. Ruri compresses cosine similarity to around 0.8, so at 0.80
    # most of the real dataset (86 episodes) merged into one giant cluster.
    # At 0.85, distinct "same shape of work" clusters (e.g. video-publishing
    # workflow, closing-entry transcription, drafting a proposal) first
    # separated cleanly, confirmed empirically (calibrated 2026-07-06).
    skill_cluster_sim: float = 0.85
    skill_nudge_min_clusters: int = 1   # nudge once at least this many clusters exist (even one recurring task is worth surfacing)
    skill_nudge_interval_days: float = 7.0  # minimum interval between nudges

    # --- Observability (perf log) ---
    # Records the duration of MCP tool calls and startup preload to
    # data_dir/perf/perf_log.jsonl. Lightweight, always-on instrumentation so
    # "something feels slow" can be diagnosed with data instead of guesswork.
    perf_log: bool = True

    # --- Auto-encoding (session-end hook) ---
    auto_encode: bool = True             # automatically save an episode from the SessionEnd hook
    auto_episode_importance: int = 3     # importance for the auto-summarized episode (low, since it's a coarse record)
    auto_encode_min_chars: int = 16      # skip recording a session whose total user text is below this length

    # --- Spontaneous recall (surface) ---
    surface_mode: str = "shadow"         # off | shadow (log only) | active (inject into context)
    surface_threshold: float = 0.45      # only memories scoring at or above this surface
    # Minimum relevance gate. No matter how high activation or importance
    # are, a memory whose lexical relevance to the utterance falls below
    # this never surfaces. This prevents frequently used, important memories
    # from intruding into unrelated contexts (observed a real case that came
    # right up against the threshold).
    surface_min_relevance: float = 0.25
    surface_max_items: int = 2           # max items injected per prompt
    surface_min_prompt_chars: int = 8    # skip recall for utterances shorter than this

    # --- Memory rooms (work/personal context separation) ---
    # {directory prefix: room name}. Matched by longest prefix; no match falls back to "common".
    room_paths: dict = field(default_factory=dict)

    @property
    def db_path(self) -> Path:
        return self.data_dir / "index.db"

    @property
    def onnx_model_dir(self) -> Path:
        """Location of the ONNX model produced by export-onnx (kept separate per model name)."""
        return self.data_dir / "onnx" / self.embed_model.replace("/", "--")


def onnx_model_ready(model_dir: Path) -> bool:
    """Whether a complete ONNX model produced by export-onnx is present (file-existence check only).

    Backs embedder.OnnxRuriEmbedder.is_available. Also used by the
    ENGRAM_PRELOAD=auto decision right at server startup, so this lives in
    this lightweight module rather than in the embedder module, which drags
    in heavy imports such as numpy.
    """
    d = Path(model_dir)
    return (
        (d / "model.onnx").is_file()
        and (d / "tokenizer.json").is_file()
        and (d / "meta.json").is_file()
    )


def config_path() -> Path:
    """Location of the user config file (generated by `engram setup`)."""
    return _engram_home() / "config.toml"


def _load_config_file() -> dict:
    path = config_path()
    if not path.is_file():
        return {}
    try:
        with path.open("rb") as f:
            return tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError):
        return {}  # a corrupt config file must not block startup (fall back to defaults)


_PATH_FIELDS = {"memories_dir", "data_dir"}
_ENV_OVERRIDES = {
    "memories_dir": "ENGRAM_MEMORIES_DIR",
    "data_dir": "ENGRAM_DATA_DIR",
    "embed_model": "ENGRAM_EMBED_MODEL",
    "embed_backend": "ENGRAM_EMBED_BACKEND",
}


def get_settings() -> Settings:
    """Return Settings, applying overrides in order: defaults < config.toml < environment variables."""
    overrides: dict = {}
    file_conf = _load_config_file()
    valid = {f.name: f.type for f in fields(Settings)}

    for key, value in file_conf.items():
        if key not in valid:
            continue
        overrides[key] = Path(value) if key in _PATH_FIELDS else value

    for key, env_name in _ENV_OVERRIDES.items():
        value = os.environ.get(env_name)
        if value:
            overrides[key] = Path(value) if key in _PATH_FIELDS else value

    return Settings(**overrides)


def resolve_room(cwd: str | Path | None, room_paths: dict) -> str:
    """Determine the memory room from the working directory.

    Matched against room_paths keys (directory prefixes) by longest match.
    Path separators (\\ and /) and case differences are normalized away.
    Falls back to "common" when nothing matches.
    """
    if not cwd or not room_paths:
        return "common"
    norm = str(cwd).replace("\\", "/").casefold().rstrip("/")
    best_len = -1
    best_room = "common"
    for prefix, room in room_paths.items():
        p = str(prefix).replace("\\", "/").casefold().rstrip("/")
        if not p:
            continue
        if (norm == p or norm.startswith(p + "/")) and len(p) > best_len:
            best_len = len(p)
            best_room = str(room)
    return best_room
